https://replit.com/@AndreaCuellar2/P2-A6-Ej-Tipo-Examen-5?v=1

print("Ingresa los ingredientes que usaste y su valor nutricional, maximo 10 ingredientes")
print("Ingresa el valor nutricional de tu primer igrediente")
ingrediente_1 = float(input())
print("Ingresa el valor nutricional de tu segundo igrediente")
ingrediente_2 = float(input())
print("Ingresa el valor nutricional de tu tercer igrediente")
ingrediente_3 = float(input())
print("Ingresa el valor nutricional de tu cuarto igrediente")
ingrediente_4 = float(input())
print("Ingresa el valor nutricional de tu quinto igrediente")
ingrediente_5 = float(input())
print("Ingresa el valor nutricional de tu sexto igrediente")
ingrediente_6 = float(input())
print("Ingresa el valor nutricional de tu septimo igrediente")
ingrediente_7 = float(input())
print("Ingresa el valor nutricional de tu octavo igrediente")
ingrediente_8 = float(input())
print("Ingresa el valor nutricional de tu noveno igrediente")
ingrediente_9 = float(input())
print("Ingresa el valor nutricional de tu decimo igrediente")
ingrediente_10 = float(input())
Valor_nutricional = (ingrediente_1+ingrediente_2+ingrediente_3+ingrediente_4+ingrediente_5+ingrediente_6+ingrediente_7+ingrediente_8+ingrediente_9+ingrediente_10)/100
print("El valor nutricional de tu comida es",Valor_nutricional)
